name: open_location_code
description: Open Location Codes are short, generated codes that can be used like street addresses, for places where street addresses don't exist.
version: 1.0.1
repository: https://github.com/FaFre/open_location_code

environment:
  sdk: ^3.2.3

dependencies:
  latlong2: ^0.9.0

dev_dependencies:
  lint: ^2.3.0
  lints: ^2.1.0
  path: ^1.9.0
  test: ^1.24.0
